### ISSUE TITLE
None of the commands are working ! help

### ISSUE THREAD

**Issue by ShubhamJ010** [jopemachine/alfred-chrome-workflow#18]
#  This is the error its been showing for all the command
```
TypeError: Cannot read properties of undefined (reading 'prepare')
    at /usr/local/lib/node_modules/alfred-chrome-workflow/src/chromeSearch.js:28:4
    at /usr/local/lib/node_modules/alfred-chrome-workflow/src/chromeSearch.js:111:3
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-chrome-workflow/src/chromeSearch.js:113:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:251206)
    at /usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:245054
    at Generator.next (<anonymous>)
    at bl (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:245412)
    at kl (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:247659)
    at Object.u (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:287740)
    at Object.o (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:287137)
```

-
alfred-chrome-workflow 0.4.1
Alfred 4.6
darwin 21.4.0

**Comment by ShubhamJ010** [comment]
<img width="731" alt="Screenshot 2022-04-22 at 4 13 34 PM" src="https://user-images.githubusercontent.com/40000538/164699880-3818ec6e-0be5-4611-b8e9-3ffeb3a2d505.png">

**Comment by jopemachine** [comment]
Thanks for letting me know.

I think maybe it is also the permission error.

Please see [this comment](https://github.com/jopemachine/alfred-chrome-workflow/issues/5#issuecomment-917042964).

And it seems like I made a mistake in error logging logic, it would be fixed in 0.4.2.

If it still doesn't work after running `chown` command, please let me know with 0.4.2's log.

**Comment by ShubhamJ010** [comment]
> Thanks for letting me know.
> 
> I think maybe it is also the permission error.
> 
> Please see [this comment](https://github.com/jopemachine/alfred-chrome-workflow/issues/5#issuecomment-917042964).
> 
> And it seems like I made a mistake in error logging logic, it would be fixed in 0.4.2.
> 
> If it still doesn't work after running `chown` command, please let me know with 0.4.2's log.

# Some kind od new error is showing up
```
Error: dlopen(/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/better-sqlite3/build/Release/better_sqlite3.node, 0x0001): tried: '/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/better-sqlite3/build/Release/better_sqlite3.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at /usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:251778
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:251820)
    at /usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:254242
    at /usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:254318
    at Su (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:228927)
    at Proxy.<anonymous> (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:254092)
    at Object.<anonymous> (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:252173)
    at Object.t (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:279775)
    at n (/usr/local/lib/node_modules/alfred-chrome-workflow/node_modules/esm/esm.js:1:279589)
```

-
alfred-chrome-workflow 0.4.1
Alfred 4.6
darwin 21.4.0

**Comment by jopemachine** [comment]
> mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')

I don't have m1 mac now, so I can't reproduce the error, but I think some `better-sqlite`'s m1 binaries might be missing on the previous version.

I just updated this workflow's dependencies, could you try to install again?

**Comment by ShubhamJ010** [comment]
> > mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')
> 
> I don't have m1 mac now, so I can't reproduce the error, but I think some `better-sqlite`'s m1 binaries might be missing on the previous version.
> 
> I just updated this workflow's dependencies, could you try to install again?

okay i will
